name: generate 3d graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      USERNAME: bekaya2344
      GITHUB_TOKEN: ${{ github.token }}

    steps:
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1

      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: profile-3d-contrib
        env:
          GITHUB_TOKEN: ${{ github.token }}
